<?xml version="1.0" encoding="UTF-8" ?>
<testsuites errors="0"
            failures="1"
            tests="1">

  <testsuite name="sample"
    errors="0" failures="1" hostname="" id="" package="sample" skipped="1"
    tests="1" time="1.017" timestamp="">
  
    <testcase name="demoTest" classname="sample" time="1.017" assertions="2">

      <failure message="Testing if element &lt;#badElement&gt; is present in 1000 ms. - expected [0;32m&#34;present&#34;[0m but got: [0;31m&#34;not present&#34;[0m">    at Object.demoTest (/Users/Lalit/LALIT/LG/DEMO_Projects/AUTOMATION/OLD/nightwatch-repo/test/sampletests/withfailures/sample.js:15:15)
    at Context.call (/Users/Lalit/LALIT/LG/DEMO_Projects/AUTOMATION/OLD/nightwatch-repo/lib/testsuite/context.js:203:32)
    at TestCase.run (/Users/Lalit/LALIT/LG/DEMO_Projects/AUTOMATION/OLD/nightwatch-repo/lib/testsuite/testcase.js:49:31)
    at Runnable.handleRunnable [as __runFn] (/Users/Lalit/LALIT/LG/DEMO_Projects/AUTOMATION/OLD/nightwatch-repo/lib/testsuite/testsuite.js:349:32)
    at Runnable.run (/Users/Lalit/LALIT/LG/DEMO_Projects/AUTOMATION/OLD/nightwatch-repo/lib/testsuite/runnable.js:123:21)
    at TestSuite.createRunnable (/Users/Lalit/LALIT/LG/DEMO_Projects/AUTOMATION/OLD/nightwatch-repo/lib/testsuite/testsuite.js:416:33)
    at TestSuite.handleRunnable (/Users/Lalit/LALIT/LG/DEMO_Projects/AUTOMATION/OLD/nightwatch-repo/lib/testsuite/testsuite.js:420:17)
    at createSession.then.then._ (/Users/Lalit/LALIT/LG/DEMO_Projects/AUTOMATION/OLD/nightwatch-repo/lib/testsuite/testsuite.js:348:21)
    at process._tickCallback (internal/process/next_tick.js:68:7)</failure>
<system-out>[[ATTACHMENT|/Users/Lalit/LALIT/LG/DEMO_Projects/AUTOMATION/OLD/nightwatch-repo/sample/demoTest_FAILED_Jan-08-2019-161343-GMT-0500-(Eastern-Standard.png]]</system-out>
    <failure message="    at Object.demoTest (/Users/Lalit/LALIT/LG/DEMO_Projects/AUTOMATION/OLD/nightwatch-repo/test/sampletests/withfailures/sample.js:15:15)">    at Context.call (/Users/Lalit/LALIT/LG/DEMO_Projects/AUTOMATION/OLD/nightwatch-repo/lib/testsuite/context.js:203:32)
    at TestCase.run (/Users/Lalit/LALIT/LG/DEMO_Projects/AUTOMATION/OLD/nightwatch-repo/lib/testsuite/testcase.js:49:31)
    at Runnable.handleRunnable [as __runFn] (/Users/Lalit/LALIT/LG/DEMO_Projects/AUTOMATION/OLD/nightwatch-repo/lib/testsuite/testsuite.js:349:32)
    at Runnable.run (/Users/Lalit/LALIT/LG/DEMO_Projects/AUTOMATION/OLD/nightwatch-repo/lib/testsuite/runnable.js:123:21)
    at TestSuite.createRunnable (/Users/Lalit/LALIT/LG/DEMO_Projects/AUTOMATION/OLD/nightwatch-repo/lib/testsuite/testsuite.js:416:33)
    at TestSuite.handleRunnable (/Users/Lalit/LALIT/LG/DEMO_Projects/AUTOMATION/OLD/nightwatch-repo/lib/testsuite/testsuite.js:420:17)
    at createSession.then.then._ (/Users/Lalit/LALIT/LG/DEMO_Projects/AUTOMATION/OLD/nightwatch-repo/lib/testsuite/testsuite.js:348:21)
    at process._tickCallback (internal/process/next_tick.js:68:7)</failure>
    </testcase>
  

  

  
    
    <testcase
      name="demoTest2" classname="sample">
      <skipped />
    </testcase>
    
  
  </testsuite>
</testsuites>
